# Generated by Django 2.0.2 on 2018-03-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasksdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=500, verbose_name='任务名称')),
                ('taskdata', models.CharField(max_length=500, verbose_name='主域名')),
            ],
        ),
    ]
